version: '3.8'

services:
  alpine-python:
    image: alpine:latest
    command: tail -f /dev/null
    ports:
      - "5001:5001"
    volumes:
      - chair_sit_consumer:/data
    tty: true
    container_name: device-status-stream-container
    environment:
      - TZ=America/Detroit
      - RELEASE_VERSION=${RELEASE_VERSION}
    networks:
      - alpine-net
    entrypoint: |
      /bin/sh -c "
      apk add --no-cache python3 py3-pip git wget;
      apk --no-cache add openjdk17-jre-headless;
      if [ ! -f /data/data/device.status-${RELEASE_VERSION}.0-SNAPSHOT.jar ]; then
        wget -O /data/device.status-${RELEASE_VERSION}-SNAPSHOT.jar https://github.com/DevinMB/sit-stats-api/releases/download/v${RELEASE_VERSION}/device.status-${RELEASE_VERSION}-SNAPSHOT.jar;
      fi
      java -jar /data/device.status-${RELEASE_VERSION}-SNAPSHOT.jar;
      "

networks:
  alpine-net:
    driver: bridge

volumes:
  chair_sit_consumer:
